### ISSUE TITLE
Godestone panics since the 6.1 maintenance ended

### ISSUE THREAD

**Issue by bourgeoisor** [xivapi/godestone#20]
**Describe the bug**
Since the Lodestone maintenance ended for 6.1, I'm unable to use Godestone to fetch character info.

**To Reproduce**

```
s := godestone.NewScraper(bingode.New(), godestone.EN)

c, err := s.FetchCharacter(32741501)
if err != nil {
log.Fatalln(err)
}

cJSON, err := json.MarshalIndent(c, "", "  ")
if err != nil {
log.Fatalln(err)
}

log.Println(string(cJSON))
```

**Expected behavior**
I expected the above code to return the character info, as it did before maintenance.

**Console output**
```
panic: runtime error: index out of range [1] with length 1

goroutine 16 [running]:
github.com/xivapi/godestone/v2.(*Scraper).buildCharacterCollector.func12(0xc0004
7e140)
        /home/finiks/go/pkg/mod/github.com/xivapi/godestone/v2@v2.2.1/character.
go:111 +0xb0
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0xc0000a2058, 0xc000
4f8000)
        /home/finiks/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074
 +0x78
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc000845b60, 0xc000159e18)
        /home/finiks/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.0/iteratio
n.go:10 +0x46
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc0003dbdc0, 0xc00047e140
)
        /home/finiks/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064
 +0x265
github.com/gocolly/colly/v2.(*Collector).fetch(0xc0003dbdc0, {0x0, 0x0}, {0xbdc1
29, 0x3}, 0x1, {0x0, 0x0}, 0xc000654150, 0xc00086a000, ...)
        /home/finiks/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676
+0x737
created by github.com/gocolly/colly/v2.(*Collector).scrape
        /home/finiks/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:574
+0x565
```

**Desktop (please complete the following information):**
Seeing this both locally (Windows 10 machine) as well as on a Google Cloud Function instance.

**Additional context**
N/A

**Comment by bourgeoisor** [comment]
Looks like it's failing here: https://github.com/xivapi/godestone/blob/main/character.go#L107-L112

Relevant CSS selector: https://github.com/xivapi/lodestone-css-selectors/blob/main/profile/character.json#L96-L99

With debug tools, I can see that both the server and DC are combined and not separated in two values like they should be:
![image](https://user-images.githubusercontent.com/3271352/163005904-738fc3a4-c9dd-40bf-a70a-e94ee2422bfa.png)

**Comment by karashiiro** [comment]
Should be fixed, now.
